// File generated by CONVERT_PALETTE macro from CPCtelera
// Converted firmware palette declaration
// 
#ifndef _mainPalette_H_
#define _mainPalette_H_

#include <types.h>

extern const u8 mainPalette[16];

#endif
